"""add order to questions

Revision ID: 0523963f0d4c
Revises: e229e74e2490
Create Date: 2025-06-19 02:20:29.130238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0523963f0d4c'
down_revision: Union[str, None] = 'e229e74e2490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('questions_survey_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'surveys', ['survey_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_survey_id_fkey'), 'questions', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'order')
    # ### end Alembic commands ###
