"""initial migration

Revision ID: e503b2e3bf2e
Revises: 
Create Date: 2025-06-24 00:52:24.408583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e503b2e3bf2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer', sa.String(), nullable=True))
    op.drop_column('answers', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'answer')
    # ### end Alembic commands ###
